version: '3.3'
services:
  code-challenge:
    image: 'obi-ogbonna-code-challenge:latest'
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: code-challenge
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - JASYPT_ENCRYPTOR_PASSWORD=c@d0ch&l%ng
      - SPRING_PROFILES_ACTIVE='dev'
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db-postgres
      - SPRING_DATASOURCE_USERNAME=db-postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=db-postgres
      - POSTGRES_PASSWORD=password