## jasypt
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

## jdoodle
jdoodle:
  clientId: DEC(+wxCajnL0+wfbvX5IEbvkUPFw98QeHZ39DEvdCWSdPFzmKygWK6OnO4JaWBdHKv0)
  clientSecret: DEC(fGEHde1xx7KPrJqOqwYYwlaXl+zg6hd/FeFH16PApJN9T0jHg0o4IkcfcgNXsuSZj2Yqn9IDYnB1xZET+FgAW8INgOvDQQ7qlSlhz1/jmfY=)
  url: https://api.jdoodle.com/v1/execute
  creditSpentUrl: https://api.jdoodle.com/v1/credit-spent

## spring
spring:
  config:
    import: tasks.yml
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: sa
    password: DEC(vvCyPH6fiCFF0WWHowib5IP4B6JMb2JT)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true