## jdoodle
jdoodle:
  clientId: ENC(uy0JDXphI6ovLTnuuy6a3d26MHn6pPfaCEFRGxiIONSMif5Kr79ZhNnT+udK3zIz)
  clientSecret: ENC(+PaJL65ruh7ZW7lFGfrlJhd6XVzUc5lMuo/zO5jleFdkyrIPBmmDR84LU7kRMLMsJEhLFNkTyzKv+fSfJ8+78yb+TxYUBpN/IQwX98GwU4E=)
  url: https://api.jdoodle.com/v1/execute
  creditSpentUrl: https://api.jdoodle.com/v1/credit-spent

## spring
spring:
  config:
    import: tasks.yml
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: sa
    password: ENC(ShTCeZ28VKSvN1QV7l0/OaFZe0GEkOfL)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true